### ISSUE TITLE
기사 본문이 끝난 후 불필요한 부분들이 포함되어 키워드 추출에 문제가 생깁니다.

### ISSUE THREAD

**Issue by linkyouhj** [ossteam8/oss8_proj#8]
네이버_블로그, 카카오톡 등이 키워드로 잘못 추출되니 불필요한 부분을 삭제해주시길 바랍니다.

**Comment by namhyo01** [comment]
위의 이슈랑 포함해서 이메일을 포함한 뒤의 내용은 제거하여 보내도록 하였습니다
